#!/usr/bin/env python3
"""Audit and calibrate the historical GWTC-4 168-scan population statistic.

This script keeps three distinct levels of inference separate:

1. **Reported historical arithmetic**: audit the published/reported aggregate
   numbers without needing the original 168 p-value vector.
2. **Observed-vector analytic statistic**: recompute the histogram and count
   statistics from the actual 168 scan-max p-values.
3. **Empirical catalog-level global calibration**: compare the observed
   aggregate statistic with complete 168-scan vectors generated by rerunning
   the identical workflow on synthetic/null catalogs.

Level 3 is the result required before describing the nominal aggregate Z as a
globally calibrated discovery significance. The scans overlap, so treating the
168 p-values as independent Uniform(0,1) values is not an adequate global null.

Historical histogram convention
--------------------------------
The paper text says "11 equal bins", but the figure and reported expected
counts explicitly use edges

    0, .05, .10, .20, .30, ..., 1.00

The first two bins therefore have width .05 and the remaining nine bins width
.10. For N=168 this gives expected counts 8.4, 8.4, then 16.8. This utility uses
the figure-compatible edges and records the textual inconsistency explicitly.
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.stats import binom, chi2, norm, poisson

HISTORICAL_EDGES = np.array(
    [0.0, 0.05, 0.10, 0.20, 0.30, 0.40, 0.50, 0.60, 0.70, 0.80, 0.90, 1.00],
    dtype=float,
)
OBSERVED_P_CANDIDATES = ("p_scanmax", "scan_null_p", "global_p", "p_value", "p")

HISTORICAL_N = 168
HISTORICAL_CHI2 = 95.6
HISTORICAL_REPORTED_P_UNIF_BOUND = 1e-15
HISTORICAL_COUNT_005 = 16
HISTORICAL_COUNT_010 = 47
HISTORICAL_REPORTED_POISSON_005 = 1.4e-3
HISTORICAL_REPORTED_POISSON_010_BOUND = 1e-10


def validate_pvalues(values: np.ndarray, label: str, expected_n: int | None = None) -> np.ndarray:
    values = np.asarray(values, dtype=float)
    if values.ndim != 1:
        raise SystemExit(f"{label} must be one-dimensional")
    if not np.all(np.isfinite(values)):
        raise SystemExit(f"{label} contains non-finite values")
    if np.any((values < 0.0) | (values > 1.0)):
        raise SystemExit(f"{label} contains values outside [0, 1]")
    if expected_n is not None and values.size != expected_n:
        raise SystemExit(f"{label} contains {values.size} values; expected {expected_n}")
    return values


def load_observed(path: Path, p_column: str | None, expected_n: int) -> tuple[np.ndarray, str]:
    df = pd.read_csv(path)
    if p_column is not None:
        if p_column not in df.columns:
            raise SystemExit(f"Observed p-value column {p_column!r} not found")
        col = p_column
    else:
        matches = [name for name in OBSERVED_P_CANDIDATES if name in df.columns]
        if len(matches) == 1:
            col = matches[0]
        elif len(matches) > 1:
            raise SystemExit(
                "Observed file contains multiple recognized p-value columns; "
                "select one with --p-column"
            )
        elif df.shape[1] == 1:
            col = str(df.columns[0])
        else:
            raise SystemExit(
                "Could not identify observed p-value column. Use --p-column. "
                f"Recognized names: {', '.join(OBSERVED_P_CANDIDATES)}"
            )
    values = validate_pvalues(df[col].to_numpy(float), "Observed p-values", expected_n)
    return values, col


def _candidate_null_columns(df: pd.DataFrame, prefix: str | None) -> list[str]:
    if prefix:
        cols = [str(c) for c in df.columns if str(c).startswith(prefix)]
        if not cols:
            raise SystemExit(f"No null-matrix columns start with prefix {prefix!r}")
        return cols

    cols: list[str] = []
    for c in df.columns:
        s = pd.to_numeric(df[c], errors="coerce")
        if s.notna().all() and ((s >= 0.0) & (s <= 1.0)).all():
            cols.append(str(c))
    return cols


def load_null_matrix(path: Path, expected_n: int, prefix: str | None) -> tuple[np.ndarray, list[str]]:
    df = pd.read_csv(path)
    cols = _candidate_null_columns(df, prefix)
    if len(cols) != expected_n:
        raise SystemExit(
            f"Null matrix has {len(cols)} candidate p-value columns; expected {expected_n}. "
            "Use --null-prefix to select the scan columns explicitly."
        )
    matrix = df[cols].to_numpy(float)
    if matrix.ndim != 2 or matrix.shape[0] == 0:
        raise SystemExit("Null matrix must contain at least one null catalog row")
    if not np.all(np.isfinite(matrix)):
        raise SystemExit("Null matrix contains non-finite values")
    if np.any((matrix < 0.0) | (matrix > 1.0)):
        raise SystemExit("Null matrix contains values outside [0, 1]")
    return matrix, cols


def histogram_chi2(pvalues: np.ndarray) -> tuple[float, np.ndarray, np.ndarray]:
    counts, _ = np.histogram(pvalues, bins=HISTORICAL_EDGES)
    widths = np.diff(HISTORICAL_EDGES)
    expected = pvalues.size * widths
    statistic = float(np.sum((counts - expected) ** 2 / expected))
    return statistic, counts.astype(int), expected


def safe_z_from_one_sided_p(p: float) -> float:
    if p <= 0.0:
        return math.inf
    if p >= 1.0:
        return -math.inf
    return float(norm.isf(p))


def empirical_upper_tail(null_stats: np.ndarray, observed: float) -> tuple[int, float]:
    ge = int(np.sum(null_stats >= observed))
    p = float((1 + ge) / (1 + null_stats.size))
    return ge, p


def count_below(pvalues: np.ndarray, threshold: float) -> int:
    return int(np.sum(pvalues < threshold))


def threshold_tail_audit(n: int, count: int, threshold: float) -> dict[str, float | int]:
    expected = float(n * threshold)
    p_poisson = float(poisson.sf(count - 1, expected))
    p_binomial = float(binom.sf(count - 1, n, threshold))
    return {
        "n": int(n),
        "threshold": float(threshold),
        "observed_count": int(count),
        "expected_count": expected,
        "poisson_upper_tail_p": p_poisson,
        "poisson_one_sided_z": safe_z_from_one_sided_p(p_poisson),
        "exact_binomial_upper_tail_p": p_binomial,
        "exact_binomial_one_sided_z": safe_z_from_one_sided_p(p_binomial),
    }


def historical_report_audit() -> dict[str, object]:
    df = len(HISTORICAL_EDGES) - 2
    chi_p = float(chi2.sf(HISTORICAL_CHI2, df=df))
    count05 = threshold_tail_audit(HISTORICAL_N, HISTORICAL_COUNT_005, 0.05)
    count10 = threshold_tail_audit(HISTORICAL_N, HISTORICAL_COUNT_010, 0.10)

    return {
        "n_scans_reported": HISTORICAL_N,
        "histogram_note": (
            "Paper text says 11 equal bins, while its figure uses [0,.05], "
            "[.05,.10], then width-.10 bins. This audit uses the figure-compatible edges."
        ),
        "histogram_edges_used": HISTORICAL_EDGES.tolist(),
        "reported_chi2": HISTORICAL_CHI2,
        "chi2_df": int(df),
        "recomputed_chi2_p": chi_p,
        "recomputed_chi2_one_sided_z": safe_z_from_one_sided_p(chi_p),
        "reported_p_unif_bound": HISTORICAL_REPORTED_P_UNIF_BOUND,
        "reported_p_unif_bound_one_sided_z": safe_z_from_one_sided_p(
            HISTORICAL_REPORTED_P_UNIF_BOUND
        ),
        "count_p_lt_0p05": {
            **count05,
            "historical_reported_poisson_p": HISTORICAL_REPORTED_POISSON_005,
            "reported_value_matches_literal_poisson": bool(
                np.isclose(
                    float(count05["poisson_upper_tail_p"]),
                    HISTORICAL_REPORTED_POISSON_005,
                    rtol=0.05,
                    atol=0.0,
                )
            ),
        },
        "count_p_lt_0p10": {
            **count10,
            "historical_reported_poisson_p_bound": HISTORICAL_REPORTED_POISSON_010_BOUND,
            "literal_poisson_satisfies_reported_bound": bool(
                float(count10["poisson_upper_tail_p"])
                < HISTORICAL_REPORTED_POISSON_010_BOUND
            ),
            "exact_binomial_satisfies_reported_bound": bool(
                float(count10["exact_binomial_upper_tail_p"])
                < HISTORICAL_REPORTED_POISSON_010_BOUND
            ),
        },
        "audit_conclusion": (
            "The reported chi-square is nominally >8 sigma under a chi-square(df=10) "
            "reference. The threshold-count arithmetic should be relabeled/recomputed: "
            "the literal Poisson tails do not reproduce the paper's stated count-tail p-values. "
            "For 47/168 below 0.10, the exact Binomial(168,0.10) tail is <1e-10, "
            "whereas the Poisson(lambda=16.8) tail is about 1.16e-9. Neither count-tail "
            "calculation addresses dependence among overlapping scans."
        ),
    }


def aggregate_summary(pvalues: np.ndarray) -> dict[str, object]:
    n = int(pvalues.size)
    chi2_stat, counts, expected = histogram_chi2(pvalues)
    chi2_p = float(chi2.sf(chi2_stat, df=len(HISTORICAL_EDGES) - 2))
    n05 = count_below(pvalues, 0.05)
    n10 = count_below(pvalues, 0.10)
    tail05 = threshold_tail_audit(n, n05, 0.05)
    tail10 = threshold_tail_audit(n, n10, 0.10)

    return {
        "n_scans": n,
        "histogram_edges": HISTORICAL_EDGES.tolist(),
        "histogram_counts": counts.tolist(),
        "histogram_expected": expected.tolist(),
        "chi2_uniformity": chi2_stat,
        "chi2_df": int(len(HISTORICAL_EDGES) - 2),
        "chi2_analytic_p": chi2_p,
        "chi2_nominal_one_sided_z": safe_z_from_one_sided_p(chi2_p),
        "count_p_lt_0p05": n05,
        "count_p_lt_0p10": n10,
        "threshold_0p05": tail05,
        "threshold_0p10": tail10,
    }


def null_stat_vectors(matrix: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    chi_stats = np.empty(matrix.shape[0], dtype=float)
    n05 = np.empty(matrix.shape[0], dtype=int)
    n10 = np.empty(matrix.shape[0], dtype=int)
    for i, row in enumerate(matrix):
        chi_stats[i] = histogram_chi2(row)[0]
        n05[i] = count_below(row, 0.05)
        n10[i] = count_below(row, 0.10)
    return chi_stats, n05, n10


def print_reported_audit(audit: dict[str, object]) -> None:
    c05 = audit["count_p_lt_0p05"]
    c10 = audit["count_p_lt_0p10"]
    assert isinstance(c05, dict) and isinstance(c10, dict)
    print("Historical reported-number audit")
    print("--------------------------------")
    print(f"Reported chi2           : {audit['reported_chi2']}")
    print(f"Recomputed chi2 p       : {float(audit['recomputed_chi2_p']):.12g}")
    print(f"Nominal chi2 Z          : {float(audit['recomputed_chi2_one_sided_z']):.6g} sigma")
    print(f"Count p<.05             : {c05['observed_count']} / {c05['n']}")
    print(f"  Poisson tail          : {float(c05['poisson_upper_tail_p']):.12g}")
    print(f"  Exact binomial tail   : {float(c05['exact_binomial_upper_tail_p']):.12g}")
    print(f"Count p<.10             : {c10['observed_count']} / {c10['n']}")
    print(f"  Poisson tail          : {float(c10['poisson_upper_tail_p']):.12g}")
    print(f"  Poisson Z             : {float(c10['poisson_one_sided_z']):.6g} sigma")
    print(f"  Exact binomial tail   : {float(c10['exact_binomial_upper_tail_p']):.12g}")
    print(f"  Exact binomial Z      : {float(c10['exact_binomial_one_sided_z']):.6g} sigma")
    print("Global calibration      : NOT ESTABLISHED BY THIS ARITHMETIC AUDIT")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Audit/calibrate the historical GWTC-4 168-scan population statistic."
    )
    parser.add_argument(
        "--audit-reported",
        action="store_true",
        help="Audit the reported chi-square/count arithmetic; does not require observed p-values",
    )
    parser.add_argument("--observed", default=None, help="CSV containing observed scan p-values")
    parser.add_argument("--p-column", default=None, help="Observed p-value column name")
    parser.add_argument(
        "--null-matrix",
        default=None,
        help="CSV: one null catalog per row, one scan p-value per column",
    )
    parser.add_argument(
        "--null-prefix",
        default=None,
        help="Optional prefix selecting p-value columns in the null matrix, e.g. scan_",
    )
    parser.add_argument("--expected-n", type=int, default=HISTORICAL_N)
    parser.add_argument(
        "--output", default="tables/gwtc4_population_global_result.json"
    )
    args = parser.parse_args()

    if args.expected_n <= 1:
        raise SystemExit("--expected-n must exceed 1")
    if args.null_matrix is not None and args.observed is None:
        raise SystemExit("--null-matrix requires --observed")
    if not args.audit_reported and args.observed is None:
        raise SystemExit("Provide --audit-reported and/or --observed")

    result: dict[str, object] = {
        "schema": "GWTC4_POPULATION_GLOBAL_NULL_V2",
        "historical_report_audit": historical_report_audit(),
        "global_calibration_status": "NOT_CALIBRATED_NO_END_TO_END_NULL_MATRIX",
    }

    if args.observed is not None:
        observed, observed_column = load_observed(
            Path(args.observed), args.p_column, args.expected_n
        )
        result["observed_file"] = str(args.observed)
        result["observed_p_column"] = observed_column
        result["observed"] = aggregate_summary(observed)
        result["interpretation"] = (
            "Observed-vector analytic p-to-Z values remain nominal until the complete "
            "correlated scan workflow is calibrated using null catalogs."
        )

        if args.null_matrix is not None:
            matrix, columns = load_null_matrix(
                Path(args.null_matrix), args.expected_n, args.null_prefix
            )
            obs = result["observed"]
            assert isinstance(obs, dict)
            chi_null, n05_null, n10_null = null_stat_vectors(matrix)

            chi_ge, chi_emp = empirical_upper_tail(
                chi_null, float(obs["chi2_uniformity"])
            )
            n05_ge, n05_emp = empirical_upper_tail(
                n05_null.astype(float), float(obs["count_p_lt_0p05"])
            )
            n10_ge, n10_emp = empirical_upper_tail(
                n10_null.astype(float), float(obs["count_p_lt_0p10"])
            )

            result["null_matrix_file"] = str(args.null_matrix)
            result["null_catalogs"] = int(matrix.shape[0])
            result["null_scan_columns"] = columns
            result["empirical_catalog_level"] = {
                "chi2_null_ge_observed": chi_ge,
                "chi2_global_p": chi_emp,
                "chi2_global_one_sided_z": safe_z_from_one_sided_p(chi_emp),
                "count_0p05_null_ge_observed": n05_ge,
                "count_0p05_global_p": n05_emp,
                "count_0p05_global_one_sided_z": safe_z_from_one_sided_p(n05_emp),
                "count_0p10_null_ge_observed": n10_ge,
                "count_0p10_global_p": n10_emp,
                "count_0p10_global_one_sided_z": safe_z_from_one_sided_p(n10_emp),
                "monte_carlo_resolution_floor": float(1.0 / (1.0 + matrix.shape[0])),
            }
            result["global_calibration_status"] = "EMPIRICALLY_CALIBRATED_FROM_NULL_MATRIX"
            result["interpretation"] = (
                "Empirical p-values compare the observed aggregate statistics with "
                "complete null-catalog 168-scan vectors, preserving whatever scan "
                "dependence is present in the supplied end-to-end null matrix."
            )

    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")

    if args.audit_reported:
        audit = result["historical_report_audit"]
        assert isinstance(audit, dict)
        print_reported_audit(audit)

    if "observed" in result:
        obs = result["observed"]
        assert isinstance(obs, dict)
        print("\nObserved 168-vector analysis")
        print("----------------------------")
        print(f"Observed scans          : {obs['n_scans']}")
        print(f"Histogram chi2          : {float(obs['chi2_uniformity']):.8g}")
        print(f"Analytic uniformity p   : {float(obs['chi2_analytic_p']):.8g}")
        print(f"Nominal one-sided Z     : {float(obs['chi2_nominal_one_sided_z']):.6g} sigma")
        print(f"Count p < 0.05          : {obs['count_p_lt_0p05']}")
        print(f"Count p < 0.10          : {obs['count_p_lt_0p10']}")

    if "empirical_catalog_level" in result:
        emp = result["empirical_catalog_level"]
        assert isinstance(emp, dict)
        print("\nEnd-to-end catalog null")
        print("-----------------------")
        print(f"Null catalogs           : {result['null_catalogs']}")
        print(f"Empirical chi2 global p : {float(emp['chi2_global_p']):.8g}")
        print(f"Empirical chi2 global Z : {float(emp['chi2_global_one_sided_z']):.6g} sigma")
        print(f"Empirical count<.10 p   : {float(emp['count_0p10_global_p']):.8g}")
        print(f"MC resolution floor     : {float(emp['monte_carlo_resolution_floor']):.8g}")

    print(f"\nWrote                   : {out}")


if __name__ == "__main__":
    main()
